<a href="https://colab.research.google.com/github/sebas-admin777/ferreyros_code/blob/main/FabricioRios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TAREA 1

1. Estudia los fundamentos de vectores y matrices

In [ ]:
# Crear 2 vectores y 2 matrizes en NumPy Realizar operaciones basicas (suma,resta,multiplicacion,division)
import numpy as np
v1 = np.array([10,20,30])
v2 = np.array([40,50,60])
#operaciones basicas}
print("Vector 1:", v1)
print("Vector 2:", v2)
print("---------------operaciones con vectores-----------")
print("suma;",v1+v2 )
print("resta;",v1-v2 )
print("multiplicacion;",v1*v2 )
print("division;",v1/v2 )

#creacion de las 2 matrizes

m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
#operaciones basicas
print("matriz 1:\n" , m1)
print("matriz 2:\n" , m2)
print("---------operaciones con matrizes---------------")
print("suma;\n",m1+m2 )
print("resta;\n",m1-m2 )
print("multiplicacion;\n",m1*m2)
print("division;\n",m1/m2 )

Vector 1: [10 20 30]
Vector 2: [40 50 60]
---------------operaciones con vectores-----------
suma; [50 70 90]
resta; [-30 -30 -30]
multiplicacion; [ 400 1000 1800]
division; [0.25 0.4  0.5 ]
matriz 1:
 [[1 2]
 [3 4]]
matriz 2:
 [[5 6]
 [7 8]]
---------operaciones con matrizes---------------
suma;
 [[ 6  8]
 [10 12]]
resta;
 [[-4 -4]
 [-4 -4]]
multiplicacion;
 [[ 5 12]
 [21 32]]
division;
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

2. Manipula y analiza estructuras de datos

Crear un DataFrame con Pandas.

In [ ]:
import pandas as pd
#Crear DataFrame
df =pd.DataFrame({
    "Producto":["A","B","C","D"],
    "Ventas": [100, 150, 80, 120],
    "Precio": [10, 12, 8, 9]
})
#columna calculada
df["Ingresos"] = df["Ventas"] * df["Precio"]

# Filtrar
print ("Productos con ventas > 100:\n", df[df["Ventas"] > 100])

# Ordenar
print("ordenando por ingresos:\n", df.sort_values(by="Ingresos", ascending=False))

#Estadisticas
print("Estadisticas:\n",df.describe())

Productos con ventas > 100:
   Producto  Ventas  Precio  Ingresos
1        B     150      12      1800
3        D     120       9      1080
ordenando por ingresos:
   Producto  Ventas  Precio  Ingresos
1        B     150      12      1800
3        D     120       9      1080
0        A     100      10      1000
2        C      80       8       640
Estadisticas:
            Ventas     Precio     Ingresos
count    4.000000   4.000000     4.000000
mean   112.500000   9.750000  1130.000000
std     29.860788   1.707825   485.935524
min     80.000000   8.000000   640.000000
25%     95.000000   8.750000   910.000000
50%    110.000000   9.500000  1040.000000
75%    127.500000  10.500000  1260.000000
max    150.000000  12.000000  1800.000000

3. Lee archivos CSV con NumPy y Pandas

SUBIMOS EL ARCHIVO CREADO S1 T1

In [15]:
import pandas as pd
df_csv = pd.read_csv('S1-T1.csv')
df_csv["Ingresos"] = df_csv["Cantidad"] * df_csv["Precio"]
print(df_csv)

    Producto  Cantidad  Precio  Ingresos
0      Mouse       100      30      3000
1    Teclado       150      25      3750
2    Monitor        10     350      3500
3  Impresora        30     650     19500

LEEMOS CON NUMPY AHORA SOLO DATOS NUMERICOS

In [18]:
import numpy as np

producto = np.loadtxt("S1-T1_1.csv", delimiter=",", skiprows=1 )

print("Datos Numpy:\n", producto)

Datos Numpy:
 [[100.  10.]
 [150.  12.]
 [ 80.   8.]
 [120.   9.]]

TAREA 2

FUNDAMENTOS DE VECTORES Y MATRICES

Actividad:

Crear una matriz con las notas de un estudiante.

Calcular la suma, promedio y transposición de una matriz de **notas**

In [19]:
import numpy as np
# Matrizes de notas (solo numeros)
notas = np.array([
    [15, 14, 18,],
    [12, 16, 14,],
    [17, 15, 19,],
    [10, 12, 11,],
    [14, 16, 13,],
])
print("Matriz de notas:\n", notas)
suma_total=np.sum(notas)
print("Suma total de notas:\n",suma_total)
suma_filas=np.sum(notas,axis=1)
print("Suma por filasÑ:\n,", suma_filas)
suma_columnas=np.sum(notas,axis=0)
print("Suma por columnas:\n", suma_columnas)
promedio_total=np.mean(notas)
print("Promedio total:\n",promedio_total)
promedio_filas=np.mean(notas,axis=1)
print("Promedio por filas:\n",promedio_filas)
promedio_columna=np.mean(notas,axis=0)
print("Promedio por columnas:\n",promedio_columna)
notas_transpuesta=notas.T
print("Matriz transpuesta:\n",notas_transpuesta)

Matriz de notas:
 [[15 14 18]
 [12 16 14]
 [17 15 19]
 [10 12 11]
 [14 16 13]]
Suma total de notas:
 216
Suma por filasÑ:
, [47 42 51 33 43]
Suma por columnas:
 [68 73 75]
Promedio total:
 14.4
Promedio por filas:
 [15.66666667 14.         17.         11.         14.33333333]
Promedio por columnas:
 [13.6 14.6 15. ]
Matriz transpuesta:
 [[15 12 17 10 14]
 [14 16 15 12 16]
 [18 14 19 11 13]]

2. Manipula y analiza estructuras de datos con panda

In [21]:
import pandas as pd
#Leer el archivo csv
estudiante=pd.read_csv('S1-T2.csv')
print(estudiante)
#Calcular promedio
estudiante["Promedio"]=estudiante[["Matematica", "Fisica", "Programacion"]].mean(axis=1)
#Calcular estado
estudiante["Estado"]=estudiante["Promedio"].apply(lambda x:"Aprobado" if x>=10.5 else "Desaprobado")
#Ordenar por promedio
tabla_ordenada=estudiante.sort_values(by="Promedio", ascending=False)
print(tabla_ordenada)

  Nombre  Matematica  Fisica  Programacion
0    Ana          15      14            18
1   Luis          12      16            14
2  Carla          17      15            19
3  Pedro          10      12            11
4  Maria          14      13            15
  Nombre  Matematica  Fisica  Programacion   Promedio    Estado
2  Carla          17      15            19  17.000000  Aprobado
0    Ana          15      14            18  15.666667  Aprobado
1   Luis          12      16            14  14.000000  Aprobado
4  Maria          14      13            15  14.000000  Aprobado
3  Pedro          10      12            11  11.000000  Aprobado

3. Lee archivos CSV con NumPy y Pandas

In [22]:
import numpy as np
#Cargar solo las notas
estudiante = np.loadtxt('S1-T2.csv', delimiter=',', skiprows=1, usecols=(1, 2, 3))
print(notas)

#Leer el CSV con nombres y notas
datos = np.genfromtxt(
  'S1-T2.csv',   #Archivo CSV
  delimiter=',',  #Separador
  dtype=None,   #Detecta tipo automáticamente
  encoding='utf-8', #Evita problemas con acentos
  skip_header=1  #Omitir la fila de encabezados

)

print(datos)

[[15 14 18]
 [12 16 14]
 [17 15 19]
 [10 12 11]
 [14 16 13]]
[('Ana', 15, 14, 18) ('Luis', 12, 16, 14) ('Carla', 17, 15, 19)
 ('Pedro', 10, 12, 11) ('Maria', 14, 13, 15)]

TAREA 3

1. Manipula y analiza estructuras de datos con panda
Actividad:
1.	Importar la librería panda.
2.	Leer el archivo S1-T3.csv.
3.	Crear la tabla producto e imprimir la tabla.

In [23]:
producto = pd.read_csv('S1-T3.csv', encoding='latin-1')
producto

        Fecha     Producto     Categoria  Cantidad  Precio_unitario  Descuento
0  2025-07-01  Paracetamol   Analgesicos        30              0.5       0.00
1  2025-07-01   Ibuprofeno   Analgesicos        20              0.8       0.05
2  2025-07-01  Amoxicilina  Antibioticos        10              1.5       0.00
3  2025-07-02  Paracetamol   Analgesicos        25              0.5       0.10
4  2025-07-02   Ibuprofeno   Analgesicos        22              0.8       0.00
5  2025-07-02    Omeprazol    Antiacidos        15              0.9       0.00
6  2025-07-03  Amoxicilina  Antibioticos         8              1.5       0.00
7  2025-07-03    VitaminaC   Suplementos        40              0.3       0.00

Agregar la columna Ingresos y calcular los Ingresos por fila = Cantidad * Precio_unitario * (1 - Descuento).

In [24]:
producto['Ingresos'] = producto['Cantidad'] * producto['Precio_unitario'] * (1 - producto['Descuento'])
producto

,Fecha,Producto,Categoria,Cantidad,Precio_unitario,Descuento,Ingresos
0,2025-07-01,Paracetamol,Analgesicos,30,0.5,0.00,15.00
1,2025-07-01,Ibuprofeno,Analgesicos,20,0.8,0.05,15.20
2,2025-07-01,Amoxicilina,Antibioticos,10,1.5,0.00,15.00
3,2025-07-02,Paracetamol,Analgesicos,25,0.5,0.10,11.25
4,2025-07-02,Ibuprofeno,Analgesicos,22,0.8,0.00,17.60
5,2025-07-02,Omeprazol,Antiacidos,15,0.9,0.00,13.50
6,2025-07-03,Amoxicilina,Antibioticos,8,1.5,0.00,12.00
7,2025-07-03,VitaminaC,Suplementos,40,0.3,0.00,12.00


Muestra las estadísticas básicas

In [25]:
print(producto.describe())

        Cantidad  Precio_unitario  Descuento   Ingresos
count   8.000000         8.000000   8.000000   8.000000
mean   21.250000         0.850000   0.018750  13.943750
std    10.593124         0.447214   0.037201   2.144334
min     8.000000         0.300000   0.000000  11.250000
25%    13.750000         0.500000   0.000000  12.000000
50%    21.000000         0.800000   0.000000  14.250000
75%    26.250000         1.050000   0.012500  15.050000
max    40.000000         1.500000   0.100000  17.600000

Ventas totales por producto (sumar Cantidad e Ingresos).

In [26]:
ventas_producto = producto.groupby('Producto').agg(
  Total_Cantidad=('Cantidad', 'sum'),
  Total_Ingresos=('Ingresos', 'sum')
).reset_index().sort_values(by='Total_Ingresos', ascending=False)


ventas_producto

      Producto  Total_Cantidad  Total_Ingresos
1   Ibuprofeno              42           32.80
0  Amoxicilina              18           27.00
3  Paracetamol              55           26.25
2    Omeprazol              15           13.50
4    VitaminaC              40           12.00

Análisis por categoría y por fecha

In [27]:
# Por categoría

ventas_categoria = producto.groupby('Categoria').agg(
  Total_Cantidad=('Cantidad','sum'),
  Total_Ingresos=('Ingresos','sum')
).reset_index()


# Por fecha (serie temporal)
ventas_dia = producto.groupby('Fecha').agg(
  Ingresos_Diarios=('Ingresos','sum'),
  Cantidad_Diaria=('Cantidad','sum')
).reset_index()

ventas_categoria, ventas_dia

(      Categoria  Total_Cantidad  Total_Ingresos
 0   Analgesicos              97           59.05
 1    Antiacidos              15           13.50
 2  Antibioticos              18           27.00
 3   Suplementos              40           12.00,
         Fecha  Ingresos_Diarios  Cantidad_Diaria
 0  2025-07-01             45.20               60
 1  2025-07-02             42.35               62
 2  2025-07-03             24.00               48)

Crear un arreglo numérico (Cantidad, Precio_unitario, Ingresos) y hacer operaciones:

In [28]:
import numpy as np
arreglo = producto[['Cantidad', 'Precio_unitario', 'Ingresos']].to_numpy() # ndarray n x 3
# Sumas y promedios
suma_total = np.sum(arreglo)       # suma de todos los valores numéricos en la submatriz
suma_por_col = np.sum(arreglo, axis=0)  # [sum Cantidad, sum Precio_unitario, sum Ingresos]
promedio_col = np.mean(arreglo, axis=0)

# Transposición
arreglo_T = arreglo.T
print("Arreglo: \n", arreglo)
print("Arreglo traspuesto : \n", arreglo_T)
print("Suma por columna:", suma_por_col)
print("Promedio por columna:", promedio_col)
print("Columnas y filas:", arreglo_T.shape)

Arreglo:
 [[30.    0.5  15.  ]
 [20.    0.8  15.2 ]
 [10.    1.5  15.  ]
 [25.    0.5  11.25]
 [22.    0.8  17.6 ]
 [15.    0.9  13.5 ]
 [ 8.    1.5  12.  ]
 [40.    0.3  12.  ]]
Arreglo traspuesto :
 [[30.   20.   10.   25.   22.   15.    8.   40.  ]
 [ 0.5   0.8   1.5   0.5   0.8   0.9   1.5   0.3 ]
 [15.   15.2  15.   11.25 17.6  13.5  12.   12.  ]]
Suma por columna: [170.     6.8  111.55]
Promedio por columna: [21.25     0.85    13.94375]
Columnas y filas: (3, 8)

Crear una tabla top_productos a partir de la tabla ventas_producto y mostrar los productos

In [29]:
top_productos = ventas_producto.head(3)

top_productos

      Producto  Total_Cantidad  Total_Ingresos
1   Ibuprofeno              42           32.80
0  Amoxicilina              18           27.00
3  Paracetamol              55           26.25